apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.3
    helm:
      values: |
        server:
          serviceType: NodePort
          serviceNodePort: 30800
          secure: false
          authModes:
            - server
        persistence:
          enabled: true
          size: 10Gi
        controller:
          workflowNamespaces:
            - argo
        images:
          tag: v4.0.3
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
