apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-builder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roberbravo/cascade
    targetRevision: master
    path: k3s/pipeline-builder
  destination:
    server: https://kubernetes.default.svc
    namespace: pipeline-builder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
