apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workdir-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
