server:
  serviceType: NodePort
  serviceNodePort: 30800
  secure: false
  authModes:
    - server

persistence:
  enabled: true
  size: 10Gi

controller:
  workflowNamespaces:
    - argo

images:
  tag: v4.0.3
